src/KendoMvcDemo.Web/Controllers/BaseController.cs
using System.Web.Mvc;
using Autofac;

namespace KendoMvcDemo.Web.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            IocContext = DependencyResolver.Current.GetService<IComponentContext>();
        }

        protected IComponentContext IocContext { get; private set; }
    }
}

src/KendoMvcDemo.Web/Controllers/ComplaintController.cs
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using KendoMvcDemo.Core.Persistence;
using KendoMvcDemo.Core.Services;
using KendoMvcDemo.Core.ViewModels;

namespace KendoMvcDemo.Web.Controllers
{
    public class ComplaintController : Controller
    {
        private readonly DataContext _db = new DataContext();
        private readonly ComplaintService _complaintService;
        private const string FORM_SEARCH_FILTER_KEY = "FORM_SEARCH_FILTER_KEY";

        public ComplaintController()
        {
            _complaintService = new ComplaintService(_db);
        }

        public ActionResult Index()
        {
            PopulateProductsDropdown();

            return View();
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            string searchTerm = TempData["FORM_SEARCH_FILTER_KEY"] as string;

            DataSourceResult result = _complaintService.Search(searchTerm).ToDataSourceResult(request);

            return Json(result);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([DataSourceRequest] DataSourceRequest request, ComplaintViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                _complaintService.Create(model);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update([DataSourceRequest] DataSourceRequest request, ComplaintViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                _complaintService.Update(model);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Destroy([DataSourceRequest] DataSourceRequest request, ComplaintViewModel model)
        {
            if (model != null)
            {
                _complaintService.Destroy(model);
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Search(FormCollection formData)
        {
            TempData["FORM_SEARCH_FILTER_KEY"] = formData["TextBoxSearchData"];

            PopulateProductsDropdown();

            return View("Index");
        }

        private void PopulateProductsDropdown()
        {
            ViewData["products"] = _db.Products.Select(x => new ProductViewModel()
            {
                ProductId = x.ProductId,
                Name = x.Name
            });
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/KendoMvcDemo.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace KendoMvcDemo.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }
    }
}

src/KendoMvcDemo.Web/Controllers/OfficeUIFabricController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KendoMvcDemo.Web.Controllers
{
    public class OfficeUIFabricController : Controller
    {
        // GET: OfficeUIFabric
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/KendoMvcDemo.Web/Controllers/ProductController.cs
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using KendoMvcDemo.Core.Services;
using KendoMvcDemo.Core.ViewModels;

namespace KendoMvcDemo.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly ProductService _productService;

        public ProductController()
        {
            _productService = new ProductService(IocContext);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            DataSourceResult result = _productService.Query().Value.ToDataSourceResult(request, c => c);

            return Json(result);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([DataSourceRequest] DataSourceRequest request, ProductViewModel product)
        {
            if (product != null && ModelState.IsValid)
            {
                _productService.Create(product);
            }

            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update([DataSourceRequest] DataSourceRequest request, ProductViewModel product)
        {
            if (product != null && ModelState.IsValid)
            {
                _productService.Update(product);
            }

            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, ProductViewModel product)
        {
            if (product != null)
            {
                _productService.Delete(product);
            }

            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }
    }
}

src/KendoMvcDemo.Web/Views/Complaint/Index.cshtml
@using (Html.BeginForm("Search", "Complaint", FormMethod.Post))
{
    <fieldset>
        <legend>Filter</legend>
        <label class="k-form-field">
            <input name="TextBoxSearchData" class="k-textbox" placeholder="Search term" />
        </label>
        <button  button type="submit" class="k-button k-primary">Search</button>
    </fieldset>
}

<br/>
@using KendoMvcDemo.Core.ViewModels
@(Html.Kendo().Grid<KendoMvcDemo.Core.ViewModels.ComplaintViewModel>()
      .Name("grid")
      .Columns(columns =>
      {
          columns.Bound(c => c.Title);
          columns.Bound(c => c.WhatHappend);
          columns.Bound(p => p.Product).ClientTemplate("#if (Product !== null) {# #=Product.Name# #} else {# No Name #} #");
          columns.Bound(c => c.Company);
          columns.Bound(c => c.SentDate);
          columns.Command(command =>
          {
              command.Edit();
              command.Destroy();
          }).Width(250);
      })
      .ToolBar(toolbar => toolbar.Create())
      .Editable(editable => editable.Mode(GridEditMode.PopUp))
      .Pageable()
      .Sortable()
      .Scrollable()
      .HtmlAttributes(new { style = "height:600px;" })
      .DataSource(dataSource => dataSource
          .Ajax()
          .PageSize(10)
          .Events(events =>
          {
              events.Error("error_handler");
              events.Sync("sync_handler");
          })
                          .Model(model =>
                          {
                              model.Id(p => p.ComplaintId);
                              model.Field(x => x.Product).DefaultValue(new ProductViewModel());
                              model.Field(x => x.Company).DefaultValue("");
                          })
                      .Create(update => update.Action("Create", "Complaint"))
                      .Read(read => read.Action("Read", "Complaint"))
                      .Update(update => update.Action("Update", "Complaint"))
                      .Destroy(update => update.Action("Destroy", "Complaint"))
                      )
)
<script type="text/javascript">

    function sync_handler() {
        //alert('sync_handler');
        var grid = $('#grid').data('grid');
        grid.dataSource.read();
    }

    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
    }
</script>

src/KendoMvcDemo.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

src/KendoMvcDemo.Web/Views/OfficeUIFabric/Index.cshtml
@model dynamic

<div class="ms-Grid">
    <div class="ms-Grid-row">
        <div class="ms-Grid-col ms-u-sm6 block">
            Kendo Office565 Theme
        </div>
        <div class="ms-Grid-col ms-u-sm6 block">
            Office Fabric
        </div>
        <div class="ms-Grid-col ms-u-sm6 block">
            @(Html.Kendo().Button()
            .Name("primaryButton")
            .HtmlAttributes(new { type = "button", @class = "k-primary" })
            .Content("Primary Button"))

            @(Html.Kendo().Button()
            .Name("textButton")
            .HtmlAttributes(new { type = "button" })
            .Content("Button"))
        </div>
        <div class="ms-Grid-col ms-u-sm6 block">
            <button class="ms-Button ms-Button--primary">
                <span class="ms-Button-label">Primary Button</span>
            </button>
            <button class="ms-Button">
                <span class="ms-Button-label">Button</span>
            </button>
        </div>
    </div>

    <div class="ms-Grid-row">
        <div class="ms-Grid-col ms-u-sm6 block">
        </div>
        <div class="ms-Grid-col ms-u-sm6 block">
        </div>
    </div>
</div>

@*https://codepen.io/andrewconnell/pen/NGNQbR*@
<style>
    .block {
        /*padding-top: 10px;
        padding-bottom: 10px;
        border: 1px black solid;
        text-align: center;
        color: white;
        background-color: gray;*/
    }
</style>

src/KendoMvcDemo.Web/Views/Product/Index.cshtml
@(Html.Kendo().Grid<KendoMvcDemo.Core.ViewModels.ProductViewModel>()
          .Name("grid")
          .Columns(columns =>
          {
              columns.Bound(p => p.Name);
              columns.Command(command => { command.Edit(); command.Destroy(); }).Width(250);
          })
          .ToolBar(toolbar => toolbar.Create())
          .Editable(editable => editable.Mode(GridEditMode.InLine).ConfirmDelete("Confirm").DisplayDeleteConfirmation("Confirm"))
          .Pageable()
          .Sortable()
          .Scrollable()
          .HtmlAttributes(new { style = "height:600px;" })
          .DataSource(dataSource => dataSource
              .Ajax()
              .PageSize(10)
              .Events(events => events.Error("error_handler"))
              .Model(model => model.Id(p => p.ProductId))
              .Create(update => update.Action("Create", "Product"))
              .Read(read => read.Action("Read", "Product"))
              .Update(update => update.Action("Update", "Product"))
              .Destroy(update => update.Action("Delete", "Product"))
          )
)
<script type="text/javascript">
    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
    }
</script>

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool?

@(Html.Kendo().CheckBoxFor(m => m))

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/ClientProduct.cshtml
@model int

    @(Html.Kendo().DropDownListFor(m => m)
              .DataValueField("ProductId")
              .DataTextField("Name")
              .BindTo((System.Collections.IEnumerable)ViewData["products"])
    )

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)      
      .HtmlAttributes(new {style="width:100%"})
      .Min(0)
)

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m))

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m))

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Email.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="email" })

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object
           
@(
 Html.Kendo().DropDownListFor(m => m)        
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
)

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
)

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Password.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="password" })

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.Kendo().TextBoxFor(model => model)

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?
           
@(Html.Kendo().TimePickerFor(m => m))

src/KendoMvcDemo.Web/Views/Shared/EditorTemplates/Url.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="url" })

src/KendoMvcDemo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - My Telerik MVC Demo</title>

    <style>
        .k-header h1 {
            margin: 0;
            padding: 30px 15px;
            font-size: 32px;
            font-weight: lighter;
        }

        html {
            position: relative;
            min-height: 100%;
        }

        body {
            margin-bottom: 60px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 60px;
            background-color: #f5f5f5;
        }
    </style>

    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.min.css">
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css">

    <link href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.common-office365.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2017.3.1026/styles/kendo.office365.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2017.3.1026/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.1026/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.1026/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2017.3.1026/js/kendo.aspnetmvc.min.js"></script>
    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
    
    <script src="https://kendo.cdn.telerik.com/2017.1.223/js/cultures/kendo.culture.en-GB.min.js"></script>
    <script type="text/javascript">
        //set current to the "en-GB" culture script
        kendo.culture("en-GB");
    </script>
 
</head>
<body>
<div>
    <div class="row k-header">
        <h1>Kendo Mvc Demo</h1>
        <div id="responsive-panel">
            @(Html.Kendo().Menu()
                  .Name("Menu")
                  .Items(items =>
                  {
                      items.Add().Text("Complaints").Action("Index", "Complaint");
                      items.Add().Text("Products").Action("Index", "Product");
                      items.Add().Text("Office UI Fabric").Action("Index", "OfficeUIFabric");
                  })
                  )
        </div>
    </div>
</div>

@RenderBody()


<div class="ms-Grid">
    <div class="ms-Grid-row">
    </div>
</div>

<footer class="footer">
    <div>
        <p class="text-muted">Copyright © 2017 GosuDev. All rights reserved.</p>
    </div>
</footer>

<script>
    $(document).ready(function() {
        $("#responsive-panel").kendoResponsivePanel({
            breakpoint: 768,
            autoClose: false,
            orientation: "top"
        });
    });

    function onclick(e) {
        $("#responsive-panel").getKendoResponsivePanel().toggle();
    }
</script>
</body>
</html>